// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Virtual_Wallet.VirtualWallet.Persistence.Data;

#nullable disable

namespace VirtualWallet.Persistence.Migrations
{
    [DbContext(typeof(WalletContext))]
    [Migration("20230810200313_initial")]
    partial class initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Virtual_Wallet.VirtualWallet.Domain.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardHolder")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CheckNumber")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("int");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCreditCard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardHolder = "Elon Musk",
                            CheckNumber = "649",
                            CurrencyCode = 3,
                            ExpirationDate = new DateTime(2025, 11, 10, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(310),
                            HasExpired = false,
                            IsCreditCard = true,
                            IsInactive = false,
                            Name = "ElonUSD",
                            Number = "8676880603590752",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CardHolder = "Jeff Bezos",
                            CheckNumber = "223",
                            CurrencyCode = 3,
                            ExpirationDate = new DateTime(2024, 10, 10, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(346),
                            HasExpired = false,
                            IsCreditCard = true,
                            IsInactive = false,
                            Name = "JeffUSD",
                            Number = "3997331179433371",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CardHolder = "Warren Buffett",
                            CheckNumber = "684",
                            CurrencyCode = 3,
                            ExpirationDate = new DateTime(2027, 5, 10, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(352),
                            HasExpired = false,
                            IsCreditCard = true,
                            IsInactive = false,
                            Name = "WarrenUSD",
                            Number = "7469810858990903",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CardHolder = "Bill Gates",
                            CheckNumber = "623",
                            CurrencyCode = 3,
                            ExpirationDate = new DateTime(2028, 2, 10, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(355),
                            HasExpired = false,
                            IsCreditCard = false,
                            IsInactive = false,
                            Name = "BillUSD",
                            Number = "7372340136556716",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CardHolder = "Larry Ellison",
                            CheckNumber = "636",
                            CurrencyCode = 3,
                            ExpirationDate = new DateTime(2026, 12, 10, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(358),
                            HasExpired = false,
                            IsCreditCard = false,
                            IsInactive = false,
                            Name = "LarryUSD",
                            Number = "4503408821426590",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CardHolder = "Mark Zuckerberg",
                            CheckNumber = "973",
                            CurrencyCode = 2,
                            ExpirationDate = new DateTime(2025, 7, 10, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(361),
                            HasExpired = false,
                            IsCreditCard = true,
                            IsInactive = false,
                            Name = "MarkEUR",
                            Number = "9539114984387891",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CardHolder = "Larry Page",
                            CheckNumber = "247",
                            CurrencyCode = 2,
                            ExpirationDate = new DateTime(2025, 10, 10, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(363),
                            HasExpired = false,
                            IsCreditCard = false,
                            IsInactive = false,
                            Name = "LarryEUR",
                            Number = "3820743154136639",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CardHolder = "Sergey Brin",
                            CheckNumber = "367",
                            CurrencyCode = 2,
                            ExpirationDate = new DateTime(2025, 1, 10, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(365),
                            HasExpired = false,
                            IsCreditCard = false,
                            IsInactive = false,
                            Name = "SergeyEUR",
                            Number = "1513410988134823",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CardHolder = "Amancio Ortega",
                            CheckNumber = "256",
                            CurrencyCode = 2,
                            ExpirationDate = new DateTime(2027, 9, 10, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(367),
                            HasExpired = false,
                            IsCreditCard = false,
                            IsInactive = false,
                            Name = "AmancioEUR",
                            Number = "4588654764785024",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CardHolder = "Carlos Slim Helu",
                            CheckNumber = "208",
                            CurrencyCode = 2,
                            ExpirationDate = new DateTime(2026, 6, 10, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(417),
                            HasExpired = false,
                            IsCreditCard = false,
                            IsInactive = false,
                            Name = "CarlosEUR",
                            Number = "3525471461987263",
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            CardHolder = "Admin",
                            CheckNumber = "543",
                            CurrencyCode = 1,
                            ExpirationDate = new DateTime(2026, 11, 10, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(420),
                            HasExpired = false,
                            IsCreditCard = true,
                            IsInactive = false,
                            Name = "AdminBGN",
                            Number = "3187868110023152",
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            CardHolder = "Elon Musk",
                            CheckNumber = "660",
                            CurrencyCode = 1,
                            ExpirationDate = new DateTime(2026, 3, 10, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(422),
                            HasExpired = false,
                            IsCreditCard = false,
                            IsInactive = false,
                            Name = "ElonBGN",
                            Number = "3896973357363677",
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CardHolder = "Warren Buffett",
                            CheckNumber = "696",
                            CurrencyCode = 1,
                            ExpirationDate = new DateTime(2027, 2, 10, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(424),
                            HasExpired = false,
                            IsCreditCard = true,
                            IsInactive = false,
                            Name = "WarrenBGN",
                            Number = "5672253593826517",
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            CardHolder = "Bill Gates",
                            CheckNumber = "994",
                            CurrencyCode = 1,
                            ExpirationDate = new DateTime(2028, 1, 10, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(426),
                            HasExpired = false,
                            IsCreditCard = true,
                            IsInactive = false,
                            Name = "BillBGN",
                            Number = "8832823205243008",
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            CardHolder = "Amancio Ortega",
                            CheckNumber = "645",
                            CurrencyCode = 1,
                            ExpirationDate = new DateTime(2025, 5, 10, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(427),
                            HasExpired = false,
                            IsCreditCard = true,
                            IsInactive = false,
                            Name = "AmancioBGN",
                            Number = "5243292944936184",
                            UserId = 9
                        });
                });

            modelBuilder.Entity("Virtual_Wallet.VirtualWallet.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 5)
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal?>("AmountReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("CurrencyExchangeRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInbound")
                        .HasColumnType("bit");

                    b.Property<int?>("RecipientId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("RecipientWalletCurrency")
                        .HasColumnType("int");

                    b.Property<int?>("SenderId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("SenderWalletCurrency")
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 111m,
                            AmountReceived = 101.03m,
                            CurrencyExchangeRate = 0.91020000000000001,
                            Date = new DateTime(2023, 7, 31, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(517),
                            Description = "Transaction",
                            IsInbound = false,
                            RecipientId = 10,
                            RecipientWalletCurrency = 2,
                            SenderId = 1,
                            SenderWalletCurrency = 3,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 2,
                            Amount = 222m,
                            AmountReceived = 202.06m,
                            CurrencyExchangeRate = 0.91020000000000001,
                            Date = new DateTime(2023, 8, 1, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(527),
                            Description = "Transfer to my friend Amancio ",
                            IsInbound = false,
                            RecipientId = 9,
                            RecipientWalletCurrency = 2,
                            SenderId = 2,
                            SenderWalletCurrency = 3,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 333m,
                            AmountReceived = 303.1m,
                            CurrencyExchangeRate = 0.91020000000000001,
                            Date = new DateTime(2023, 8, 2, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(531),
                            Description = "buying new car",
                            IsInbound = false,
                            RecipientId = 8,
                            RecipientWalletCurrency = 2,
                            SenderId = 3,
                            SenderWalletCurrency = 3,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 444m,
                            AmountReceived = 790.59m,
                            CurrencyExchangeRate = 1.7806,
                            Date = new DateTime(2023, 8, 3, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(535),
                            Description = "Payment over invoice 12345678",
                            IsInbound = false,
                            RecipientId = 7,
                            RecipientWalletCurrency = 1,
                            SenderId = 4,
                            SenderWalletCurrency = 3,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 555m,
                            AmountReceived = 555m,
                            CurrencyExchangeRate = 0.0,
                            Date = new DateTime(2023, 8, 4, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(537),
                            Description = "Invoice 22446688",
                            IsInbound = false,
                            RecipientId = 6,
                            RecipientWalletCurrency = 1,
                            SenderId = 5,
                            SenderWalletCurrency = 1,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 666m,
                            AmountReceived = 1185.88m,
                            CurrencyExchangeRate = 1.7806,
                            Date = new DateTime(2023, 8, 5, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(541),
                            Description = "Deposit for vacation",
                            IsInbound = false,
                            RecipientId = 11,
                            RecipientWalletCurrency = 1,
                            SenderId = 1,
                            SenderWalletCurrency = 3,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 200m,
                            CardNumber = "************0752",
                            Date = new DateTime(2023, 8, 6, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(544),
                            Description = "Some cash for my wallet ;)",
                            IsInbound = false,
                            RecipientId = 1,
                            SenderId = 1,
                            SenderWalletCurrency = 3,
                            TransactionType = 3
                        },
                        new
                        {
                            Id = 8,
                            Amount = 1024m,
                            CardNumber = "************3371",
                            Date = new DateTime(2023, 8, 6, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(546),
                            Description = "Transfer from card",
                            IsInbound = false,
                            RecipientId = 2,
                            SenderId = 2,
                            SenderWalletCurrency = 3,
                            TransactionType = 3
                        },
                        new
                        {
                            Id = 9,
                            Amount = 50000m,
                            CardNumber = "************7891",
                            Date = new DateTime(2023, 8, 6, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(548),
                            Description = "Transfer from card",
                            IsInbound = false,
                            RecipientId = 6,
                            SenderId = 6,
                            SenderWalletCurrency = 1,
                            TransactionType = 3
                        },
                        new
                        {
                            Id = 10,
                            Amount = 1200m,
                            AmountReceived = 2136.72m,
                            CurrencyExchangeRate = 1.7806,
                            Date = new DateTime(2023, 8, 6, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(550),
                            Description = "Pay my rent",
                            IsInbound = false,
                            RecipientId = 6,
                            RecipientWalletCurrency = 1,
                            SenderId = 1,
                            SenderWalletCurrency = 3,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 11,
                            Amount = 505.55m,
                            AmountReceived = 283.61m,
                            CurrencyExchangeRate = 0.56159999999999999,
                            Date = new DateTime(2023, 8, 6, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(552),
                            Description = "Give Warren some coins",
                            IsInbound = false,
                            RecipientId = 3,
                            RecipientWalletCurrency = 3,
                            SenderId = 5,
                            SenderWalletCurrency = 1,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 12,
                            Amount = 33.24m,
                            AmountReceived = 18.53m,
                            CurrencyExchangeRate = 0.56159999999999999,
                            Date = new DateTime(2023, 8, 7, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(556),
                            Description = "payment",
                            IsInbound = false,
                            RecipientId = 1,
                            RecipientWalletCurrency = 3,
                            SenderId = 6,
                            SenderWalletCurrency = 1,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 13,
                            Amount = 156m,
                            CardNumber = "************6716",
                            Date = new DateTime(2023, 8, 7, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(558),
                            Description = "why not to cash back some money",
                            IsInbound = false,
                            RecipientId = 4,
                            SenderId = 4,
                            SenderWalletCurrency = 3,
                            TransactionType = 4
                        },
                        new
                        {
                            Id = 14,
                            Amount = 22.99m,
                            CardNumber = "************3371",
                            Date = new DateTime(2023, 8, 7, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(560),
                            Description = "personal stuff",
                            IsInbound = false,
                            RecipientId = 4,
                            SenderId = 4,
                            SenderWalletCurrency = 3,
                            TransactionType = 3
                        },
                        new
                        {
                            Id = 15,
                            Amount = 50m,
                            CardNumber = "************0752",
                            Date = new DateTime(2023, 8, 7, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(562),
                            Description = "I am transfering some money back to my card",
                            IsInbound = false,
                            RecipientId = 1,
                            SenderId = 1,
                            SenderWalletCurrency = 3,
                            TransactionType = 4
                        },
                        new
                        {
                            Id = 16,
                            Amount = 0.01m,
                            AmountReceived = 0.01m,
                            CurrencyExchangeRate = 0.0,
                            Date = new DateTime(2023, 8, 8, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(564),
                            Description = "donation",
                            IsInbound = false,
                            RecipientId = 2,
                            RecipientWalletCurrency = 3,
                            SenderId = 1,
                            SenderWalletCurrency = 3,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 17,
                            Amount = 12225.35m,
                            AmountReceived = 12225.35m,
                            CurrencyExchangeRate = 0.0,
                            Date = new DateTime(2023, 8, 8, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(567),
                            Description = "Payment for invoice 223332556",
                            IsInbound = false,
                            RecipientId = 3,
                            RecipientWalletCurrency = 3,
                            SenderId = 1,
                            SenderWalletCurrency = 3,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 18,
                            Amount = 336m,
                            AmountReceived = 336m,
                            CurrencyExchangeRate = 0.0,
                            Date = new DateTime(2023, 8, 8, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(570),
                            Description = "Invoice 103104105",
                            IsInbound = false,
                            RecipientId = 2,
                            RecipientWalletCurrency = 3,
                            SenderId = 1,
                            SenderWalletCurrency = 3,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 19,
                            Amount = 1024m,
                            CardNumber = "************3371",
                            Date = new DateTime(2023, 8, 8, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(572),
                            Description = "Transfer from card",
                            IsInbound = false,
                            RecipientId = 1,
                            SenderId = 1,
                            SenderWalletCurrency = 3,
                            TransactionType = 3
                        },
                        new
                        {
                            Id = 20,
                            Amount = 1566m,
                            CardNumber = "************3371",
                            Date = new DateTime(2023, 8, 8, 23, 3, 13, 411, DateTimeKind.Local).AddTicks(574),
                            Description = "Transfer from card",
                            IsInbound = false,
                            RecipientId = 1,
                            SenderId = 1,
                            SenderWalletCurrency = 3,
                            TransactionType = 3
                        });
                });

            modelBuilder.Entity("Virtual_Wallet.VirtualWallet.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("nvarchar(170)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(170)
                        .HasColumnType("nvarchar(170)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "elon@musk.com",
                            FirstName = "Elon",
                            IsAdmin = true,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Musk",
                            Password = "z3cYHVk1R4my8gZeon0xrHmfDE8Vpxd5j7QTpIvc3GM=",
                            PhoneNumber = "1234567890",
                            Photo = "images/users/elon_musk.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "ElonMusk",
                            VerifiedAt = new DateTime(2023, 8, 4, 23, 3, 13, 353, DateTimeKind.Local).AddTicks(346),
                            WalletId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "jeff@amazon.com",
                            FirstName = "Jeff",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Bezos",
                            Password = "p3zsqKJ0kKcdPlp9wSUJtBAP7H9EZ1D1C9miQv32JkU=",
                            PhoneNumber = "9876543210",
                            Photo = "images/users/jeff_bezos.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "JeffBezos",
                            VerifiedAt = new DateTime(2023, 8, 4, 23, 3, 13, 357, DateTimeKind.Local).AddTicks(1117),
                            WalletId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "warren@berkshire.com",
                            FirstName = "Warren",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Buffett",
                            Password = "n7p8JbjMz1idjRo1BwE2ldlT4rHSxVxGhwQKMT2YIgg=",
                            PhoneNumber = "9876543210",
                            Photo = "images/users/warren_buffett.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "WarrenBuffett",
                            VerifiedAt = new DateTime(2023, 8, 5, 23, 3, 13, 361, DateTimeKind.Local).AddTicks(1488),
                            WalletId = 3
                        },
                        new
                        {
                            Id = 4,
                            Email = "BillGates@gmaill.com",
                            FirstName = "Bill",
                            IsAdmin = true,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Gates",
                            Password = "ljrqrV6Ma5F+Z8Q4O4MhRWt9+6b8YXlaQCfFNmVFOoc=",
                            PhoneNumber = "1234567890",
                            Photo = "images/users/bill_gates.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "BillGates",
                            VerifiedAt = new DateTime(2023, 8, 5, 23, 3, 13, 365, DateTimeKind.Local).AddTicks(2314),
                            WalletId = 4
                        },
                        new
                        {
                            Id = 5,
                            Email = "larry@oracle.com",
                            FirstName = "Larry",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Ellison",
                            Password = "yWItNvpeF65jhQ4lIBSZug2OEw1vOLgqORfMwqAH/AE=",
                            PhoneNumber = "9876543210",
                            Photo = "images/users/larry_ellison.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "LarryEllison",
                            VerifiedAt = new DateTime(2023, 8, 7, 23, 3, 13, 369, DateTimeKind.Local).AddTicks(3027),
                            WalletId = 5
                        },
                        new
                        {
                            Id = 6,
                            Email = "mark@facebook.com",
                            FirstName = "Mark",
                            IsAdmin = true,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Zuckerberg",
                            Password = "aAIBn4DcscHU4QfinnbAq76vHXEca+ruz+r7Q1+m+yA=",
                            PhoneNumber = "1234567890",
                            Photo = "images/users/mark_zuckerberg.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "MarkZuckerberg",
                            VerifiedAt = new DateTime(2023, 8, 8, 23, 3, 13, 373, DateTimeKind.Local).AddTicks(3992),
                            WalletId = 6
                        },
                        new
                        {
                            Id = 7,
                            Email = "larry@google.com",
                            FirstName = "Larry",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Page",
                            Password = "UHRkaY7AmMrwMQMx8yL45Qjwrjhgsdcn2RwppcDM6Ro=",
                            PhoneNumber = "9876543210",
                            Photo = "images/users/larry_page.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "LarryPage",
                            VerifiedAt = new DateTime(2023, 8, 8, 23, 3, 13, 377, DateTimeKind.Local).AddTicks(4729),
                            WalletId = 7
                        },
                        new
                        {
                            Id = 8,
                            Email = "sergey@google.com",
                            FirstName = "Sergey",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Brin",
                            Password = "ogHZo0NPhyhEMdJfs1jGUGjnKf/s4awGIuuYy8025ok=",
                            PhoneNumber = "1234567890",
                            Photo = "images/users/sergey_brin.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "SergeyBrin",
                            VerifiedAt = new DateTime(2023, 8, 8, 23, 3, 13, 381, DateTimeKind.Local).AddTicks(6657),
                            WalletId = 8
                        },
                        new
                        {
                            Id = 9,
                            Email = "amancio@zara.com",
                            FirstName = "Amancio",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Ortega",
                            Password = "D5iGczcroSmodpIen53mk2Fj/21O4MusmC6GKb01QF8=",
                            PhoneNumber = "9876543210",
                            Photo = "images/users/amancio_ortega.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "AmancioOrtega",
                            VerifiedAt = new DateTime(2023, 8, 9, 23, 3, 13, 385, DateTimeKind.Local).AddTicks(7686),
                            WalletId = 9
                        },
                        new
                        {
                            Id = 10,
                            Email = "carlos@telmex.com",
                            FirstName = "Carlos",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "SlimHelu",
                            Password = "cJuzqjHngfuzVhEQFZUEFKaAP+N7qHF+AjJxPdluHaI=",
                            PhoneNumber = "1234567890",
                            Photo = "images/users/carlos_slim_helu.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "CarlosSlimHelu",
                            VerifiedAt = new DateTime(2023, 8, 9, 23, 3, 13, 389, DateTimeKind.Local).AddTicks(8588),
                            WalletId = 10
                        },
                        new
                        {
                            Id = 11,
                            Email = "mkm_vw@abv.bg",
                            FirstName = "Admin",
                            IsAdmin = true,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Adminov",
                            Password = "mGCUINPf0hSqMTwCdcnxoQWdGEhsJrYOpjpvQarWLFo=",
                            PhoneNumber = "1234567890",
                            Photo = "images/users/defaultProfile.png",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "Admin",
                            VerifiedAt = new DateTime(2023, 8, 9, 23, 3, 13, 394, DateTimeKind.Local).AddTicks(175),
                            WalletId = 11
                        },
                        new
                        {
                            Id = 12,
                            Email = "User@user.com",
                            FirstName = "User",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Userov",
                            Password = "mGCUINPf0hSqMTwCdcnxoQWdGEhsJrYOpjpvQarWLFo=",
                            PhoneNumber = "1234567890",
                            Photo = "images/users/defaultProfile.png",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "User",
                            VerifiedAt = new DateTime(2023, 8, 9, 23, 3, 13, 398, DateTimeKind.Local).AddTicks(1775)
                        },
                        new
                        {
                            Id = 13,
                            Email = "GwShotwell@SpaceX.com",
                            FirstName = "Gwynne",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Shotwell",
                            Password = "mGCUINPf0hSqMTwCdcnxoQWdGEhsJrYOpjpvQarWLFo=",
                            PhoneNumber = "1224364852",
                            Photo = "images/users/GwynneShotwell.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "GwynneShotwell",
                            VerifiedAt = new DateTime(2023, 8, 9, 23, 3, 13, 402, DateTimeKind.Local).AddTicks(3454),
                            WalletId = 12
                        },
                        new
                        {
                            Id = 14,
                            Email = "SafraCatz@Oracle.com",
                            FirstName = "Safra",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            LastName = "Catz",
                            Password = "mGCUINPf0hSqMTwCdcnxoQWdGEhsJrYOpjpvQarWLFo=",
                            PhoneNumber = "1234567890",
                            Photo = "images/users/SafraCatz.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "SafraCatz",
                            VerifiedAt = new DateTime(2023, 8, 9, 23, 3, 13, 406, DateTimeKind.Local).AddTicks(6782)
                        });
                });

            modelBuilder.Entity("Virtual_Wallet.VirtualWallet.Domain.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(20, 5)
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Blocked")
                        .HasPrecision(20, 5)
                        .HasColumnType("decimal(20,5)");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("int");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 111111.11m,
                            Blocked = 0m,
                            CurrencyCode = 3,
                            IsInactive = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Balance = 99999.99m,
                            Blocked = 0m,
                            CurrencyCode = 3,
                            IsInactive = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Balance = 88888.88m,
                            Blocked = 0m,
                            CurrencyCode = 3,
                            IsInactive = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Balance = 77777.77m,
                            Blocked = 0m,
                            CurrencyCode = 3,
                            IsInactive = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Balance = 66666.66m,
                            Blocked = 0m,
                            CurrencyCode = 1,
                            IsInactive = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Balance = 55555.55m,
                            Blocked = 0m,
                            CurrencyCode = 1,
                            IsInactive = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Balance = 44444.44m,
                            Blocked = 0m,
                            CurrencyCode = 1,
                            IsInactive = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Balance = 33333.33m,
                            Blocked = 0m,
                            CurrencyCode = 2,
                            IsInactive = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Balance = 22222.22m,
                            Blocked = 0m,
                            CurrencyCode = 2,
                            IsInactive = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Balance = 11111.11m,
                            Blocked = 0m,
                            CurrencyCode = 2,
                            IsInactive = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            Balance = 9999.99m,
                            Blocked = 0m,
                            CurrencyCode = 1,
                            IsInactive = false,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            Balance = 0.00m,
                            Blocked = 0m,
                            CurrencyCode = 1,
                            IsInactive = false,
                            UserId = 13
                        });
                });

            modelBuilder.Entity("Virtual_Wallet.VirtualWallet.Domain.Entities.Card", b =>
                {
                    b.HasOne("Virtual_Wallet.VirtualWallet.Domain.Entities.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Virtual_Wallet.VirtualWallet.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Virtual_Wallet.VirtualWallet.Domain.Entities.User", "Recipient")
                        .WithMany("ReceivedTransactions")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Virtual_Wallet.VirtualWallet.Domain.Entities.User", "Sender")
                        .WithMany("SentTransactions")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Virtual_Wallet.VirtualWallet.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("Virtual_Wallet.VirtualWallet.Domain.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("Virtual_Wallet.VirtualWallet.Domain.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Virtual_Wallet.VirtualWallet.Domain.Entities.User", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("ReceivedTransactions");

                    b.Navigation("SentTransactions");

                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
