// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Virtual_Wallet.VirtualWallet.Persistence.Data;

#nullable disable

namespace VirtualWallet.Persistence.Migrations
{
    [DbContext(typeof(WalletContext))]
    partial class WalletContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Virtual_Wallet.VirtualWallet.Domain.Entities.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("CardHolder")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("CheckNumber")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("HasExpired")
                        .HasColumnType("bit");

                    b.Property<bool>("IsCreditCard")
                        .HasColumnType("bit");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("Cards");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CardHolder = "Elon Musk",
                            CheckNumber = "649",
                            ExpirationDate = new DateTime(2025, 11, 2, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2026),
                            HasExpired = false,
                            IsCreditCard = true,
                            IsInactive = false,
                            Number = "8676880603590752",
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            CardHolder = "Jeff Bezos",
                            CheckNumber = "223",
                            ExpirationDate = new DateTime(2024, 10, 2, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2039),
                            HasExpired = false,
                            IsCreditCard = true,
                            IsInactive = false,
                            Number = "3997331179433371",
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            CardHolder = "Warren Buffett",
                            CheckNumber = "684",
                            ExpirationDate = new DateTime(2027, 5, 2, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2043),
                            HasExpired = false,
                            IsCreditCard = true,
                            IsInactive = false,
                            Number = "7469810858990903",
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            CardHolder = "Bill Gates",
                            CheckNumber = "623",
                            ExpirationDate = new DateTime(2028, 2, 2, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2046),
                            HasExpired = false,
                            IsCreditCard = false,
                            IsInactive = false,
                            Number = "7372340136556716",
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            CardHolder = "Larry Ellison",
                            CheckNumber = "636",
                            ExpirationDate = new DateTime(2026, 12, 2, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2049),
                            HasExpired = false,
                            IsCreditCard = false,
                            IsInactive = false,
                            Number = "4503408821426590",
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            CardHolder = "Mark Zuckerberg",
                            CheckNumber = "973",
                            ExpirationDate = new DateTime(2025, 7, 2, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2052),
                            HasExpired = false,
                            IsCreditCard = true,
                            IsInactive = false,
                            Number = "9539114984387891",
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            CardHolder = "Larry Page",
                            CheckNumber = "247",
                            ExpirationDate = new DateTime(2025, 10, 2, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2054),
                            HasExpired = false,
                            IsCreditCard = false,
                            IsInactive = false,
                            Number = "3820743154136639",
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            CardHolder = "Sergey Brin",
                            CheckNumber = "367",
                            ExpirationDate = new DateTime(2025, 1, 2, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2057),
                            HasExpired = false,
                            IsCreditCard = false,
                            IsInactive = false,
                            Number = "1513410988134823",
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            CardHolder = "Amancio Ortega",
                            CheckNumber = "256",
                            ExpirationDate = new DateTime(2027, 9, 2, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2059),
                            HasExpired = false,
                            IsCreditCard = false,
                            IsInactive = false,
                            Number = "4588654764785024",
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            CardHolder = "Carlos Slim Helu",
                            CheckNumber = "208",
                            ExpirationDate = new DateTime(2026, 6, 2, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2062),
                            HasExpired = false,
                            IsCreditCard = false,
                            IsInactive = false,
                            Number = "3525471461987263",
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            CardHolder = "Admin",
                            CheckNumber = "543",
                            ExpirationDate = new DateTime(2026, 11, 2, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2063),
                            HasExpired = false,
                            IsCreditCard = true,
                            IsInactive = false,
                            Number = "3187868110023152",
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            CardHolder = "Elon Musk",
                            CheckNumber = "660",
                            ExpirationDate = new DateTime(2026, 3, 2, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2066),
                            HasExpired = false,
                            IsCreditCard = false,
                            IsInactive = false,
                            Number = "3896973357363677",
                            UserId = 1
                        },
                        new
                        {
                            Id = 13,
                            CardHolder = "Warren Buffett",
                            CheckNumber = "696",
                            ExpirationDate = new DateTime(2027, 2, 2, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2068),
                            HasExpired = false,
                            IsCreditCard = true,
                            IsInactive = false,
                            Number = "5672253593826517",
                            UserId = 3
                        },
                        new
                        {
                            Id = 14,
                            CardHolder = "Bill Gates",
                            CheckNumber = "994",
                            ExpirationDate = new DateTime(2028, 1, 2, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2070),
                            HasExpired = false,
                            IsCreditCard = true,
                            IsInactive = false,
                            Number = "8832823205243008",
                            UserId = 4
                        },
                        new
                        {
                            Id = 15,
                            CardHolder = "Amancio Ortega",
                            CheckNumber = "645",
                            ExpirationDate = new DateTime(2025, 5, 2, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2073),
                            HasExpired = false,
                            IsCreditCard = true,
                            IsInactive = false,
                            Number = "5243292944936184",
                            UserId = 9
                        });
                });

            modelBuilder.Entity("Virtual_Wallet.VirtualWallet.Domain.Entities.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(20, 5)
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal?>("AmountReceived")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CardNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("CurrencyExchangeRate")
                        .HasColumnType("float");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInbound")
                        .HasColumnType("bit");

                    b.Property<int?>("RecipientId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int?>("SenderId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RecipientId");

                    b.HasIndex("SenderId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amount = 111m,
                            AmountReceived = 101.03m,
                            CurrencyExchangeRate = 0.91020000000000001,
                            Date = new DateTime(2023, 7, 23, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2147),
                            Description = "Transaction",
                            IsInbound = false,
                            RecipientId = 10,
                            SenderId = 1,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 2,
                            Amount = 222m,
                            AmountReceived = 202.06m,
                            CurrencyExchangeRate = 0.91020000000000001,
                            Date = new DateTime(2023, 7, 24, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2157),
                            Description = "Transfer to my friend Amancio ",
                            IsInbound = false,
                            RecipientId = 9,
                            SenderId = 2,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 3,
                            Amount = 333m,
                            AmountReceived = 303.1m,
                            CurrencyExchangeRate = 0.91020000000000001,
                            Date = new DateTime(2023, 7, 25, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2161),
                            Description = "buying new car",
                            IsInbound = false,
                            RecipientId = 8,
                            SenderId = 3,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 4,
                            Amount = 444m,
                            AmountReceived = 790.59m,
                            CurrencyExchangeRate = 1.7806,
                            Date = new DateTime(2023, 7, 26, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2163),
                            Description = "Payment over invoice 12345678",
                            IsInbound = false,
                            RecipientId = 7,
                            SenderId = 4,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 5,
                            Amount = 555m,
                            AmountReceived = 555m,
                            CurrencyExchangeRate = 0.0,
                            Date = new DateTime(2023, 7, 27, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2166),
                            Description = "Invoice 22446688",
                            IsInbound = false,
                            RecipientId = 6,
                            SenderId = 5,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 6,
                            Amount = 666m,
                            AmountReceived = 1185.88m,
                            CurrencyExchangeRate = 1.7806,
                            Date = new DateTime(2023, 7, 28, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2169),
                            Description = "Deposit for vacation",
                            IsInbound = false,
                            RecipientId = 11,
                            SenderId = 1,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 7,
                            Amount = 200m,
                            CardNumber = "************0752",
                            Date = new DateTime(2023, 7, 29, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2171),
                            Description = "Some cash for my wallet ;)",
                            IsInbound = false,
                            RecipientId = 1,
                            SenderId = 1,
                            TransactionType = 3
                        },
                        new
                        {
                            Id = 8,
                            Amount = 1024m,
                            CardNumber = "************3371",
                            Date = new DateTime(2023, 7, 29, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2240),
                            Description = "Transfer from card",
                            IsInbound = false,
                            RecipientId = 2,
                            SenderId = 2,
                            TransactionType = 3
                        },
                        new
                        {
                            Id = 9,
                            Amount = 50000m,
                            CardNumber = "************7891",
                            Date = new DateTime(2023, 7, 29, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2243),
                            Description = "Transfer from card",
                            IsInbound = false,
                            RecipientId = 6,
                            SenderId = 6,
                            TransactionType = 3
                        },
                        new
                        {
                            Id = 10,
                            Amount = 1200m,
                            AmountReceived = 2136.72m,
                            CurrencyExchangeRate = 1.7806,
                            Date = new DateTime(2023, 7, 29, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2246),
                            Description = "Pay my rent",
                            IsInbound = false,
                            RecipientId = 6,
                            SenderId = 1,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 11,
                            Amount = 505.55m,
                            AmountReceived = 283.61m,
                            CurrencyExchangeRate = 0.56159999999999999,
                            Date = new DateTime(2023, 7, 29, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2249),
                            Description = "Give Warren some coins",
                            IsInbound = false,
                            RecipientId = 3,
                            SenderId = 5,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 12,
                            Amount = 33.24m,
                            AmountReceived = 18.53m,
                            CurrencyExchangeRate = 0.56159999999999999,
                            Date = new DateTime(2023, 7, 30, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2251),
                            Description = "payment",
                            IsInbound = false,
                            RecipientId = 1,
                            SenderId = 6,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 13,
                            Amount = 156m,
                            CardNumber = "************6716",
                            Date = new DateTime(2023, 7, 30, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2254),
                            Description = "why not to cash back some money",
                            IsInbound = false,
                            RecipientId = 4,
                            SenderId = 4,
                            TransactionType = 4
                        },
                        new
                        {
                            Id = 14,
                            Amount = 22.99m,
                            CardNumber = "************3371",
                            Date = new DateTime(2023, 7, 30, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2256),
                            Description = "personal stuff",
                            IsInbound = false,
                            RecipientId = 4,
                            SenderId = 4,
                            TransactionType = 3
                        },
                        new
                        {
                            Id = 15,
                            Amount = 50m,
                            CardNumber = "************0752",
                            Date = new DateTime(2023, 7, 30, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2257),
                            Description = "I am transfering some money back to my card",
                            IsInbound = false,
                            RecipientId = 1,
                            SenderId = 1,
                            TransactionType = 4
                        },
                        new
                        {
                            Id = 16,
                            Amount = 0.01m,
                            AmountReceived = 0.01m,
                            CurrencyExchangeRate = 0.0,
                            Date = new DateTime(2023, 7, 31, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2259),
                            Description = "donation",
                            IsInbound = false,
                            RecipientId = 2,
                            SenderId = 1,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 17,
                            Amount = 12225.35m,
                            AmountReceived = 12225.35m,
                            CurrencyExchangeRate = 0.0,
                            Date = new DateTime(2023, 7, 31, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2262),
                            Description = "Payment for invoice 223332556",
                            IsInbound = false,
                            RecipientId = 3,
                            SenderId = 1,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 18,
                            Amount = 336m,
                            AmountReceived = 336m,
                            CurrencyExchangeRate = 0.0,
                            Date = new DateTime(2023, 7, 31, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2267),
                            Description = "Invoice 103104105",
                            IsInbound = false,
                            RecipientId = 2,
                            SenderId = 1,
                            TransactionType = 2
                        },
                        new
                        {
                            Id = 19,
                            Amount = 1024m,
                            CardNumber = "************3371",
                            Date = new DateTime(2023, 7, 31, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2270),
                            Description = "Transfer from card",
                            IsInbound = false,
                            RecipientId = 1,
                            SenderId = 1,
                            TransactionType = 3
                        },
                        new
                        {
                            Id = 20,
                            Amount = 1566m,
                            CardNumber = "************3371",
                            Date = new DateTime(2023, 7, 31, 15, 11, 17, 865, DateTimeKind.Local).AddTicks(2271),
                            Description = "Transfer from card",
                            IsInbound = false,
                            RecipientId = 1,
                            SenderId = 1,
                            TransactionType = 3
                        });
                });

            modelBuilder.Entity("Virtual_Wallet.VirtualWallet.Domain.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<bool>("IsBlocked")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(170)
                        .HasColumnType("nvarchar(170)");

                    b.Property<string>("PhoneNumber")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("Photo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("VerificationToken")
                        .HasMaxLength(170)
                        .HasColumnType("nvarchar(170)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.Property<int?>("WalletId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "elon@musk.com",
                            IsAdmin = true,
                            IsBlocked = false,
                            IsDeleted = false,
                            Password = "z3cYHVk1R4my8gZeon0xrHmfDE8Vpxd5j7QTpIvc3GM=",
                            PhoneNumber = "1234567890",
                            Photo = "elon_musk.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "ElonMusk",
                            VerifiedAt = new DateTime(2023, 7, 27, 15, 11, 17, 774, DateTimeKind.Local).AddTicks(5973),
                            WalletId = 1
                        },
                        new
                        {
                            Id = 2,
                            Email = "jeff@amazon.com",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            Password = "p3zsqKJ0kKcdPlp9wSUJtBAP7H9EZ1D1C9miQv32JkU=",
                            PhoneNumber = "9876543210",
                            Photo = "jeff_bezos.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "JeffBezos",
                            VerifiedAt = new DateTime(2023, 7, 27, 15, 11, 17, 780, DateTimeKind.Local).AddTicks(8489),
                            WalletId = 2
                        },
                        new
                        {
                            Id = 3,
                            Email = "warren@berkshire.com",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            Password = "n7p8JbjMz1idjRo1BwE2ldlT4rHSxVxGhwQKMT2YIgg=",
                            PhoneNumber = "9876543210",
                            Photo = "warren_buffett.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "WarrenBuffett",
                            VerifiedAt = new DateTime(2023, 7, 28, 15, 11, 17, 787, DateTimeKind.Local).AddTicks(5303),
                            WalletId = 3
                        },
                        new
                        {
                            Id = 4,
                            Email = "BillGates@gmaill.com",
                            IsAdmin = true,
                            IsBlocked = false,
                            IsDeleted = false,
                            Password = "ljrqrV6Ma5F+Z8Q4O4MhRWt9+6b8YXlaQCfFNmVFOoc=",
                            PhoneNumber = "1234567890",
                            Photo = "bill_gates.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "BillGates",
                            VerifiedAt = new DateTime(2023, 7, 28, 15, 11, 17, 794, DateTimeKind.Local).AddTicks(4311),
                            WalletId = 4
                        },
                        new
                        {
                            Id = 5,
                            Email = "larry@oracle.com",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            Password = "yWItNvpeF65jhQ4lIBSZug2OEw1vOLgqORfMwqAH/AE=",
                            PhoneNumber = "9876543210",
                            Photo = "larry_ellison.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "LarryEllison",
                            VerifiedAt = new DateTime(2023, 7, 30, 15, 11, 17, 800, DateTimeKind.Local).AddTicks(7377),
                            WalletId = 5
                        },
                        new
                        {
                            Id = 6,
                            Email = "mark@facebook.com",
                            IsAdmin = true,
                            IsBlocked = false,
                            IsDeleted = false,
                            Password = "aAIBn4DcscHU4QfinnbAq76vHXEca+ruz+r7Q1+m+yA=",
                            PhoneNumber = "1234567890",
                            Photo = "mark_zuckerberg.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "MarkZuckerberg",
                            VerifiedAt = new DateTime(2023, 7, 31, 15, 11, 17, 807, DateTimeKind.Local).AddTicks(279),
                            WalletId = 6
                        },
                        new
                        {
                            Id = 7,
                            Email = "larry@google.com",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            Password = "UHRkaY7AmMrwMQMx8yL45Qjwrjhgsdcn2RwppcDM6Ro=",
                            PhoneNumber = "9876543210",
                            Photo = "larry_page.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "LarryPage",
                            VerifiedAt = new DateTime(2023, 7, 31, 15, 11, 17, 813, DateTimeKind.Local).AddTicks(2394),
                            WalletId = 7
                        },
                        new
                        {
                            Id = 8,
                            Email = "sergey@google.com",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            Password = "ogHZo0NPhyhEMdJfs1jGUGjnKf/s4awGIuuYy8025ok=",
                            PhoneNumber = "1234567890",
                            Photo = "sergey_brin.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "SergeyBrin",
                            VerifiedAt = new DateTime(2023, 7, 31, 15, 11, 17, 819, DateTimeKind.Local).AddTicks(7472),
                            WalletId = 8
                        },
                        new
                        {
                            Id = 9,
                            Email = "amancio@zara.com",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            Password = "D5iGczcroSmodpIen53mk2Fj/21O4MusmC6GKb01QF8=",
                            PhoneNumber = "9876543210",
                            Photo = "amancio_ortega.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "AmancioOrtega",
                            VerifiedAt = new DateTime(2023, 8, 1, 15, 11, 17, 826, DateTimeKind.Local).AddTicks(5452),
                            WalletId = 9
                        },
                        new
                        {
                            Id = 10,
                            Email = "carlos@telmex.com",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            Password = "cJuzqjHngfuzVhEQFZUEFKaAP+N7qHF+AjJxPdluHaI=",
                            PhoneNumber = "1234567890",
                            Photo = "carlos_slim_helu.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "CarlosSlimHelu",
                            VerifiedAt = new DateTime(2023, 8, 1, 15, 11, 17, 832, DateTimeKind.Local).AddTicks(8778),
                            WalletId = 10
                        },
                        new
                        {
                            Id = 11,
                            Email = "mkm_vw@abv.bg",
                            IsAdmin = true,
                            IsBlocked = false,
                            IsDeleted = false,
                            Password = "mGCUINPf0hSqMTwCdcnxoQWdGEhsJrYOpjpvQarWLFo=",
                            PhoneNumber = "1234567890",
                            Photo = "Admin.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "Admin",
                            VerifiedAt = new DateTime(2023, 8, 1, 15, 11, 17, 839, DateTimeKind.Local).AddTicks(1772),
                            WalletId = 11
                        },
                        new
                        {
                            Id = 12,
                            Email = "User@user.com",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            Password = "mGCUINPf0hSqMTwCdcnxoQWdGEhsJrYOpjpvQarWLFo=",
                            PhoneNumber = "1234567890",
                            Photo = "User.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "User",
                            VerifiedAt = new DateTime(2023, 8, 1, 15, 11, 17, 845, DateTimeKind.Local).AddTicks(4331),
                            WalletId = 12
                        },
                        new
                        {
                            Id = 13,
                            Email = "GwShotwell@SpaceX.com",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            Password = "mGCUINPf0hSqMTwCdcnxoQWdGEhsJrYOpjpvQarWLFo=",
                            PhoneNumber = "1224364852",
                            Photo = "User.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "GwynneShotwell",
                            VerifiedAt = new DateTime(2023, 8, 1, 15, 11, 17, 852, DateTimeKind.Local).AddTicks(1053),
                            WalletId = 12
                        },
                        new
                        {
                            Id = 14,
                            Email = "SafraCatz@Oracle.com",
                            IsAdmin = false,
                            IsBlocked = false,
                            IsDeleted = false,
                            Password = "mGCUINPf0hSqMTwCdcnxoQWdGEhsJrYOpjpvQarWLFo=",
                            PhoneNumber = "1234567890",
                            Photo = "User.jpg",
                            Salt = "aYkdwwd7tFrZOsBA2Za0qQ==",
                            Username = "SafraCatz",
                            VerifiedAt = new DateTime(2023, 8, 1, 15, 11, 17, 858, DateTimeKind.Local).AddTicks(8089),
                            WalletId = 12
                        });
                });

            modelBuilder.Entity("Virtual_Wallet.VirtualWallet.Domain.Entities.Wallet", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Balance")
                        .HasPrecision(20, 5)
                        .HasColumnType("decimal(20,5)");

                    b.Property<decimal>("Blocked")
                        .HasPrecision(20, 5)
                        .HasColumnType("decimal(20,5)");

                    b.Property<int>("CurrencyCode")
                        .HasColumnType("int");

                    b.Property<bool>("IsInactive")
                        .HasColumnType("bit");

                    b.Property<int?>("UserId")
                        .IsRequired()
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Wallets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Balance = 111111.11m,
                            Blocked = 0m,
                            CurrencyCode = 3,
                            IsInactive = false,
                            UserId = 1
                        },
                        new
                        {
                            Id = 2,
                            Balance = 99999.99m,
                            Blocked = 0m,
                            CurrencyCode = 3,
                            IsInactive = false,
                            UserId = 2
                        },
                        new
                        {
                            Id = 3,
                            Balance = 88888.88m,
                            Blocked = 0m,
                            CurrencyCode = 3,
                            IsInactive = false,
                            UserId = 3
                        },
                        new
                        {
                            Id = 4,
                            Balance = 77777.77m,
                            Blocked = 0m,
                            CurrencyCode = 3,
                            IsInactive = false,
                            UserId = 4
                        },
                        new
                        {
                            Id = 5,
                            Balance = 66666.66m,
                            Blocked = 0m,
                            CurrencyCode = 1,
                            IsInactive = false,
                            UserId = 5
                        },
                        new
                        {
                            Id = 6,
                            Balance = 55555.55m,
                            Blocked = 0m,
                            CurrencyCode = 1,
                            IsInactive = false,
                            UserId = 6
                        },
                        new
                        {
                            Id = 7,
                            Balance = 44444.44m,
                            Blocked = 0m,
                            CurrencyCode = 1,
                            IsInactive = false,
                            UserId = 7
                        },
                        new
                        {
                            Id = 8,
                            Balance = 33333.33m,
                            Blocked = 0m,
                            CurrencyCode = 2,
                            IsInactive = false,
                            UserId = 8
                        },
                        new
                        {
                            Id = 9,
                            Balance = 22222.22m,
                            Blocked = 0m,
                            CurrencyCode = 2,
                            IsInactive = false,
                            UserId = 9
                        },
                        new
                        {
                            Id = 10,
                            Balance = 11111.11m,
                            Blocked = 0m,
                            CurrencyCode = 2,
                            IsInactive = false,
                            UserId = 10
                        },
                        new
                        {
                            Id = 11,
                            Balance = 9999.99m,
                            Blocked = 0m,
                            CurrencyCode = 1,
                            IsInactive = false,
                            UserId = 11
                        },
                        new
                        {
                            Id = 12,
                            Balance = 0.00m,
                            Blocked = 0m,
                            CurrencyCode = 1,
                            IsInactive = false,
                            UserId = 12
                        });
                });

            modelBuilder.Entity("Virtual_Wallet.VirtualWallet.Domain.Entities.Card", b =>
                {
                    b.HasOne("Virtual_Wallet.VirtualWallet.Domain.Entities.User", "User")
                        .WithMany("Cards")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Virtual_Wallet.VirtualWallet.Domain.Entities.Transaction", b =>
                {
                    b.HasOne("Virtual_Wallet.VirtualWallet.Domain.Entities.User", "Recipient")
                        .WithMany("ReceivedTransactions")
                        .HasForeignKey("RecipientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Virtual_Wallet.VirtualWallet.Domain.Entities.User", "Sender")
                        .WithMany("SentTransactions")
                        .HasForeignKey("SenderId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Recipient");

                    b.Navigation("Sender");
                });

            modelBuilder.Entity("Virtual_Wallet.VirtualWallet.Domain.Entities.Wallet", b =>
                {
                    b.HasOne("Virtual_Wallet.VirtualWallet.Domain.Entities.User", "User")
                        .WithOne("Wallet")
                        .HasForeignKey("Virtual_Wallet.VirtualWallet.Domain.Entities.Wallet", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Virtual_Wallet.VirtualWallet.Domain.Entities.User", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("ReceivedTransactions");

                    b.Navigation("SentTransactions");

                    b.Navigation("Wallet");
                });
#pragma warning restore 612, 618
        }
    }
}
